#ifndef GENICAM_CAMERA_XML_H
#define GENICAM_CAMERA_XML_H

const char* genicam_xml_default_content =
    "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n"
    "<RegisterDescription\n"
    "    ModelName=\"MyCamera\"\n"
    "    VendorName=\"MyCompany\"\n"
    "    ToolTip=\"Minimal GigE Vision Camera\"\n"
    "    StandardNameSpace=\"None\"\n"
    "    SchemaMajorVersion=\"1\"\n"
    "    SchemaMinorVersion=\"1\"\n"
    "    SchemaSubMinorVersion=\"0\"\n"
    "    MajorVersion=\"1\"\n"
    "    MinorVersion=\"0\"\n"
    "    SubMinorVersion=\"0\"\n"
    "    xmlns=\"http://www.genicam.org/GenApi/Version_1_1\"\n"
    "    xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"\n"
    "    xsi:schemaLocation=\"http://www.genicam.org/GenApi/Version_1_1 http://www.genicam.org/GenApi/GenApiSchema_Version_1_1.xsd\">\n"
    "\n"
    "    <!-- Root category -->\n"
    "    <Category Name=\"Root\">\n"
    "        <ToolTip>Root node for traversing the camera features</ToolTip>\n"
    "        <pFeature>DeviceControl</pFeature>\n"
    "        <pFeature>ImageFormatControl</pFeature>\n"
    "    </Category>\n"
    "\n"
    "    <!-- Device control -->\n"
    "    <Category Name=\"DeviceControl\">\n"
    "        <ToolTip>Device control features</ToolTip>\n"
    "        <pFeature>DeviceVendorName</pFeature>\n"
    "        <pFeature>DeviceModelName</pFeature>\n"
    "        <pFeature>DeviceVersion</pFeature>\n"
    "        <pFeature>DeviceManufacturerInfo</pFeature>\n"
    "        <pFeature>DeviceID</pFeature>\n"
    "    </Category>\n"
    "    <!-- Device control -->\n"
    "\n"
    "    <Category Name=\"DeviceControl\" NameSpace=\"Standard\">\n"
    "        <pFeature>DeviceVendorName</pFeature>\n"
    "        <pFeature>DeviceModelName</pFeature>\n"
    "        <pFeature>DeviceManufacturerInfo</pFeature>\n"
    "        <pFeature>DeviceID</pFeature>\n"
    "        <pFeature>DeviceVersion</pFeature>\n"
    "    </Category>\n"
    "\n"
    "    <StringReg Name=\"DeviceVendorName\" NameSpace=\"Standard\">\n"
    "        <DisplayName>Vendor Name</DisplayName>\n"
    "        <Address>0x48</Address>\n"
    "        <Length>32</Length>\n"
    "        <AccessMode>RO</AccessMode>\n"
    "        <pPort>Device</pPort>\n"
    "    </StringReg>\n"
    "\n"
    "    <StringReg Name=\"DeviceModelName\" NameSpace=\"Standard\">\n"
    "        <DisplayName>Model Name</DisplayName>\n"
    "        <Address>0x68</Address>\n"
    "        <Length>32</Length>\n"
    "        <AccessMode>RO</AccessMode>\n"
    "        <pPort>Device</pPort>\n"
    "    </StringReg>\n"
    "\n"
    "    <StringReg Name=\"DeviceManufacturerInfo\" NameSpace=\"Standard\">\n"
    "        <DisplayName>Manufacturer Info</DisplayName>\n"
    "        <Address>0xa8</Address>\n"
    "        <Length>48</Length>\n"
    "        <AccessMode>RO</AccessMode>\n"
    "        <pPort>Device</pPort>\n"
    "    </StringReg>\n"
    "\n"
    "    <StringReg Name=\"DeviceID\" NameSpace=\"Standard\">\n"
    "        <DisplayName>Device ID</DisplayName>\n"
    "        <Address>0xd8</Address>\n"
    "        <Length>16</Length>\n"
    "        <AccessMode>RO</AccessMode>\n"
    "        <pPort>Device</pPort>\n"
    "    </StringReg>\n"
    "\n"
    "    <StringReg Name=\"DeviceVersion\" NameSpace=\"Standard\">\n"
    "        <DisplayName>Device Version</DisplayName>\n"
    "        <Address>0x88</Address>\n"
    "        <Length>32</Length>\n"
    "        <AccessMode>RO</AccessMode>\n"
    "        <pPort>Device</pPort>\n"
    "    </StringReg>\n"
    "\n"
    "    <!-- Image format control -->\n"
    "\n"
    "    <Category Name=\"ImageFormatControl\" NameSpace=\"Standard\">\n"
    "        <pFeature>SensorHeight</pFeature>\n"
    "        <pFeature>SensorWidth</pFeature>\n"
    "        <pFeature>Width</pFeature>\n"
    "        <pFeature>Height</pFeature>\n"
    "        <pFeature>PixelFormat</pFeature>\n"
    "    </Category>\n"
    "\n"
    "    <Integer Name=\"SensorHeight\" NameSpace=\"Standard\">\n"
    "        <Description>Full height of image sensor.</Description>\n"
    "        <pValue>SensorHeightRegister</pValue>\n"
    "    </Integer>\n"
    "\n"
    "    <IntReg Name=\"SensorHeightRegister\" NameSpace=\"Custom\">\n"
    "        <Address>0x118</Address>\n"
    "        <Length>4</Length>\n"
    "        <AccessMode>RO</AccessMode>\n"
    "        <pPort>Device</pPort>\n"
    "        <Sign>Unsigned</Sign>\n"
    "        <Endianess>BigEndian</Endianess>\n"
    "    </IntReg>\n"
    "\n"
    "    <Integer Name=\"SensorWidth\" NameSpace=\"Standard\">\n"
    "        <Description>Full height of image sensor.</Description>\n"
    "        <pValue>SensorWidthRegister</pValue>\n"
    "    </Integer>\n"
    "\n"
    "    <IntReg Name=\"SensorWidthRegister\" NameSpace=\"Custom\">\n"
    "        <Address>0x11c</Address>\n"
    "        <Length>4</Length>\n"
    "        <AccessMode>RO</AccessMode>\n"
    "        <pPort>Device</pPort>\n"
    "        <Sign>Unsigned</Sign>\n"
    "        <Endianess>BigEndian</Endianess>\n"
    "    </IntReg>\n"
    "\n"
    "    <Integer Name=\"Width\" NameSpace=\"Standard\">\n"
    "        <Description>Width of image, in pixels.</Description>\n"
    "        <pValue>WidthRegister</pValue>\n"
    "        <Min>1</Min>\n"
    "        <pMax>SensorWidth</pMax>\n"
    "        <Inc>1</Inc>\n"
    "    </Integer>\n"
    "\n"
    "    <IntReg Name=\"WidthRegister\" NameSpace=\"Custom\">\n"
    "        <Address>0x100</Address>\n"
    "        <Length>4</Length>\n"
    "        <AccessMode>RW</AccessMode>\n"
    "        <pPort>Device</pPort>\n"
    "        <Sign>Unsigned</Sign>\n"
    "        <Endianess>BigEndian</Endianess>\n"
    "    </IntReg>\n"
    "\n"
    "    <Integer Name=\"Height\" NameSpace=\"Standard\">\n"
    "        <Description>Height of image, in pixels.</Description>\n"
    "        <pValue>HeightRegister</pValue>\n"
    "        <Min>1</Min>\n"
    "        <pMax>SensorHeight</pMax>\n"
    "        <Inc>1</Inc>\n"
    "    </Integer>\n"
    "\n"
    "    <IntReg Name=\"HeightRegister\" NameSpace=\"Custom\">\n"
    "        <Address>0x104</Address>\n"
    "        <Length>4</Length>\n"
    "        <AccessMode>RW</AccessMode>\n"
    "        <pPort>Device</pPort>\n"
    "        <Sign>Unsigned</Sign>\n"
    "        <Endianess>BigEndian</Endianess>\n"
    "    </IntReg>\n"
    "\n"
    "    <!-- Pixel format -->\n"
    "    <Enumeration Name=\"PixelFormat\" NameSpace=\"Standard\">\n"
    "        <DisplayName>Pixel format</DisplayName>\n"
    "        <EnumEntry Name=\"Mono8\" NameSpace=\"Standard\">\n"
    "            <Value>17301505</Value>\n"
    "        </EnumEntry>\n"
    "        <EnumEntry Name=\"Mono16\" NameSpace=\"Standard\">\n"
    "            <Value>17825799</Value>\n"
    "        </EnumEntry>\n"
    "        <pValue>PixelFormatRegister</pValue>\n"
    "    </Enumeration>\n"
    "\n"
    "    <IntReg Name=\"PixelFormatRegister\" NameSpace=\"Custom\">\n"
    "        <Address>0x128</Address>\n"
    "        <Length>4</Length>\n"
    "        <AccessMode>RW</AccessMode>\n"
    "        <pPort>Device</pPort>\n"
    "        <Sign>Unsigned</Sign>\n"
    "        <Endianess>BigEndian</Endianess>\n"
    "    </IntReg>\n"
    "\n"
    "    <!-- Port -->\n"
    "\n"
    "    <Port Name=\"Device\" NameSpace=\"Standard\">\n"
    "    </Port>\n"
    "\n"
    "</RegisterDescription>\n";

#endif // GENICAM_CAMERA_XML_H
